#!/bin/bash

xrandr --output HDMI-1 --off

devices=$(xinput list | grep 'Wacom Pen' | grep -o 'id=[0-9]*' | grep -o '[0-9]*')

for device in $devices
do
  xinput map-to-output $device eDP-1
done

# set a random liked background
feh --bg-fill --randomize ~/.var/backgrounds/liked/*
