#!/bin/bash

xrandr --output HDMI-1 --auto
xrandr --output HDMI-1 --right-of eDP-1

xinput map-to-output 10 eDP-1
xinput map-to-output 15 eDP-1
xinput map-to-output 20 eDP-1

# set a random liked background
feh --bg-fill --randomize ~/.var/backgrounds/liked/*
