#!/bin/bash

# turn xresources into environment variables
xrdb -load ~/.config/tanaica/Xresources 
xrdb_output=$(xrdb -query)

while IFS= read -r line; do
  if [[ "$line" =~ \* ]]; then
    line=$(echo "$line" | sed "s/\*//")
    name=$(echo "$line" | cut -d':' -f1 | tr -d '[:space:]')
    value=$(echo "$line" | cut -d':' -f2 | tr -d '[:space:]')
    export $name=$value
  fi
done <<< "$xrdb_output"

# load environment from .env
while read -r line; do
  if [[ "$line" =~ = ]]; then
    name=$(echo "$line" | cut -d'=' -f1)
    value=$(echo "$line" | cut -d'=' -f2)
    export $name=$value
  fi
done <<< $(cat .config/tanaica/env)

# Use zsh in i3
export SHELL=/bin/zsh

# ensure password manager will work
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# set a random liked background
feh --bg-fill --randomize ~/.var/backgrounds/liked/*

# if the variable DEFAULT_KEYBOARD is set, set the keyboard layout
if [ -n "$DEFAULT_KEYBOARD" ]; then
  setxkbmap $DEFAULT_KEYBOARD
fi

# map the pen input device to the integrated screen
xinput map-to-output 12 eDP-1
xinput map-to-output 19 eDP-1

# theme
export GTK_THEME=Layan:dark

# browser
export BROWSER=pulse-browser

echo '3-5' | tee /sys/bus/usb/drivers/usb/unbind

# start i3
i3
